security:
  oauth2:
    client:
      clientId: 705445061234-hg27gdnem5jnfqlob55a0eb3as885lfh.apps.googleusercontent.com
      clientSecret: C37y08WpHjV6Immj6zIYWWPr
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v1/certs